---
apiVersion: apps/v1

{{- if .Values.scaling.stateful }}
kind: StatefulSet
{{- else }}
kind: Deployment
{{- end }}

metadata:
  name: {{ .Release.Name }}
  labels: {{ toJson .Values.workload.labels }}

spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.scaling.replicas }}
  progressDeadlineSeconds: {{ .Values.workload.startupTimeout }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: pocketmine
          image: pmmp/pocketmine-mp:{{ .Values.pocketmine.version }}
          ports:
            - containerPort: 19132
              protocol: UDP
              name: minecraft
          volumeMounts:
            - name: plugins
              mountPath: /plugins
              readOnly: true
            - name: data
              mountPath: /data
      volumes:
        - name: plugins
          hostPath:
            {{- if .Values.plugins.downloader.path }}
            path: {{ .Values.plugins.downloader.path }}
            {{- else }}
            path: /tmp/pocketmine-plugin-downloader/{{ .Release.Namespace }}/{{ .Release.Name }}
            {{- end }}
            type: DirectoryOrCreate
      {{- if not .Values.scaling.stateful }}
        - name: data
          configMap:
            name: data
            items:
              - key: server.properties
                path: server.properties
              - key: pocketmine.yml
                path: pocketmine.yml
      {{- end }}
  {{- if .Values.scaling.stateful }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "" # TODO
  {{- end }}
...
