{{ if .Values.plugins.downloader.enabled }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-plugin-downloader
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-plugin-downloader
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-plugin-downloader
    spec:
      containers:
        - name: plugin-downloader
          image: ghcr.io/pmmp/pocketmine-helm/plugin-downloader:dev
          volumeMounts:
            - name: plugins
              mountPath: /mnt/plugins
              subPath: {{ .Release.Namespace }}
      volumes:
        - name: plugins
          hostPath:
            {{- if .Values.plugins.downloader.path }}
            path: {{ .Values.plugins.downloader.path }}
            {{- else }}
            path: /tmp/pocketmine-plugin-downloader/{{ .Release.Namespace }}/{{ .Release.Name }}
            {{- end }}
            type: DirectoryOrCreate
      serviceAccountName: {{ .Release.Name }}-plugin-downloader
...
{{- end }}
