name: Update Docker images

on:
  push:
  release:
    types: [published]

jobs:
  build:
    name: Update Docker images
    runs-on: ubuntu-20.04

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Docker build
        run: |
          docker build --tag plugin-downloader --target plugin-downloader .
          docker build --tag server-manager --target server-manager .

      - name: Docker push
        run: |
          if [ "${{ github.event }}" == release ]; then
            TAG=$(echo "${{ github.ref }}" | sed 's#^refs/tags/##')
          else
            TAG=dev
          fi
          docker tag plugin-downloader ghcr.io/pmmp/pocketmine-helm/plugin-downloader:$TAG
          docker push ghcr.io/pmmp/pocketmine-helm/plugin-downloader:$TAG

          docker tag server-manager ghcr.io/pmmp/pocketmine-helm/server-manager:$TAG
          docker push ghcr.io/pmmp/pocketmine-helm/server-manager:$TAG
